import { AuthProvider } from '@/contexts/auth/AuthProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '../../components/NavBar'
import { SessionProvider } from "next-auth/react"
import ClientSessionProvider from '../../utils/SessionProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClientSessionProvider>
      <AuthProvider>
        <html lang="en">
          <body className={inter.className}>
            {children}
          </body>
        </html>
      </AuthProvider>
    </ClientSessionProvider>
  )
}
